import { NodeTemplate } from "@/types/workflow";

export const actionTemplates: NodeTemplate[] = [
  {
    id: "slack",
    label: "Slack",
    icon: "slack",
    category: "actions",
    color: "#4A154B",
    description: "Send message to a Slack channel",
    configFields: [
      { name: "credential_id", label: "Slack Account", type: "credential" },
      { name: "channel", label: "Channel", type: "text", placeholder: "#general or C1234567890" },
      { name: "message", label: "Message", type: "textarea", placeholder: "Enter message..." },
    ],
  },
  {
    id: "gmail",
    label: "Gmail",
    icon: "gmail",
    category: "actions",
    color: "#3b82f6",
    description: "Send email via Gmail",
    configFields: [
      { name: "to", label: "To", type: "text", placeholder: "recipient@example.com" },
      { name: "subject", label: "Subject", type: "text", placeholder: "Email subject" },
      { name: "body", label: "Body", type: "textarea", placeholder: "Email body..." },
    ],
  },
  {
    id: "whatsapp",
    label: "WhatsApp",
    icon: "whatsapp",
    category: "actions",
    color: "#25D366",
    description: "Send WhatsApp message",
    configFields: [
      { name: "phone", label: "Phone Number", type: "text", placeholder: "919876543210" },
      { name: "message", label: "Message", type: "textarea", placeholder: "Enter message..." },
      { name: "credential_id", label: "Credential", type: "credential" },
    ],
  },


  {
    id: "http",
    label: "HTTP Request",
    icon: "globe",
    category: "actions",
    color: "#3b82f6",
    description: "Make HTTP request",
    configFields: [
      { name: "url", label: "URL", type: "text", placeholder: "https://api.example.com" },
      { name: "method", label: "Method", type: "select", options: [
        { label: "GET", value: "GET" },
        { label: "POST", value: "POST" },
        { label: "PUT", value: "PUT" },
        { label: "DELETE", value: "DELETE" },
      ]},
      { name: "headers", label: "Headers (JSON)", type: "textarea", placeholder: '{"Authorization": "Bearer ..."}' },
      { name: "body", label: "Body (JSON)", type: "textarea", placeholder: '{"key": "value"}' },
    ],
  },
  {
    id: "database",
    label: "Database",
    icon: "database",
    category: "actions",
    color: "#3b82f6",
    description: "Query SQL (Postgres/MySQL) or MongoDB databases",
    configFields: [
      {
        name: "db_type",
        label: "Database Type",
        type: "select",
        options: [
          { label: "PostgreSQL", value: "postgres" },
          { label: "MySQL", value: "mysql" },
          { label: "MongoDB", value: "mongodb" },
        ],
        defaultValue: "postgres",
      },
      {
        name: "connection_type",
        label: "Connection Method",
        type: "select",
        options: [
          { label: "Connection URL / URI String", value: "connection_string" },
          { label: "Host, Port, User credentials", value: "credential_fields" },
        ],
        defaultValue: "connection_string",
      },
      {
        name: "connection_string",
        label: "Connection URL / URI",
        type: "text",
        placeholder: "postgresql://user:pass@localhost:5432/dbname or mongodb://...",
        showWhen: { field: "connection_type", value: "connection_string" },
      },
      {
        name: "host",
        label: "Host / IP Address",
        type: "text",
        placeholder: "localhost",
        showWhen: { field: "connection_type", value: "credential_fields" },
      },
      {
        name: "port",
        label: "Port",
        type: "number",
        placeholder: "e.g., 5432 or 27017",
        showWhen: { field: "connection_type", value: "credential_fields" },
      },
      {
        name: "username",
        label: "Username",
        type: "text",
        placeholder: "Database user name",
        showWhen: { field: "connection_type", value: "credential_fields" },
      },
      {
        name: "password",
        label: "Password",
        type: "text",
        placeholder: "Database password",
        showWhen: { field: "connection_type", value: "credential_fields" },
      },
      {
        name: "database_name",
        label: "Database Name",
        type: "text",
        placeholder: "Target database name",
      },
      {
        name: "query",
        label: "SQL Query (PostgreSQL)",
        type: "textarea",
        placeholder: "SELECT * FROM users LIMIT 10;",
        showWhen: { field: "db_type", value: "postgres" },
      },
      {
        name: "query_mysql",
        label: "SQL Query (MySQL)",
        type: "textarea",
        placeholder: "SELECT * FROM users LIMIT 10;",
        showWhen: { field: "db_type", value: "mysql" },
      },
      {
        name: "mongodb_collection",
        label: "Collection Name",
        type: "text",
        placeholder: "e.g. users",
        showWhen: { field: "db_type", value: "mongodb" },
      },
      {
        name: "mongodb_operation",
        label: "Operation",
        type: "select",
        options: [
          { label: "Find (Select)", value: "find" },
          { label: "Insert One", value: "insert" },
          { label: "Update Many", value: "update" },
          { label: "Delete Many", value: "delete" },
        ],
        showWhen: { field: "db_type", value: "mongodb" },
      },
      {
        name: "mongodb_query",
        label: "Query JSON Document",
        type: "textarea",
        placeholder: '{"name": "Alice"} or {"filter": {"id": 1}, "update": {"$set": {"status": "active"}}}',
        showWhen: { field: "db_type", value: "mongodb" },
      },
    ],
  },
  {
    id: "code",
    label: "Code",
    icon: "code",
    category: "actions",
    color: "#3b82f6",
    description: "Run custom Python code",
    configFields: [
      {
        name: "code",
        label: "Python Code",
        type: "code",
        placeholder: "# input_data has outputs from previous nodes\n# set output_data dict to pass data forward"
      },
    ],
  },
  {
    id: "playwright",
    label: "Browser Automation",
    icon: "globe",
    category: "actions",
    color: "#6366f1",
    description: "Automate web browser with Playwright",
    configFields: [
      { name: "url", label: "Target URL", type: "text", placeholder: "https://example.com" },
      { name: "script", label: "Playwright Script (Python)", type: "code", placeholder: "# page is available\ncontent = await page.content()\noutput_data = {'html': content}" },
    ],
  },
  {
    id: "resend",
    label: "Resend Email",
    icon: "mail",
    category: "actions",
    color: "#3b82f6",
    description: "Send email using Resend",
    configFields: [
      { name: "from", label: "From", type: "text", placeholder: "onboarding@resend.dev" },
      { name: "to", label: "To", type: "text", placeholder: "recipient@example.com" },
      { name: "subject", label: "Subject", type: "text", placeholder: "Email subject" },
      { name: "html", label: "HTML Body", type: "textarea", placeholder: "<p>Hello from Noderift</p>" },
      { name: "credential_id", label: "Credential", type: "credential" },
    ],
  },
  {
    id: "composio",
    label: "Composio",
    icon: "box",
    category: "actions",
    color: "#f59e0b",
    description: "Run integration actions via Composio",
    configFields: [
      { name: "app", label: "App", type: "select", options: [
        { label: "Gmail", value: "gmail" },
        { label: "Slack", value: "slack" },
      ]},
      { name: "action", label: "Action", type: "select", options: [
        { label: "Gmail - Send Email", value: "GMAIL_SEND_EMAIL" },
        { label: "Slack - Send Message", value: "SLACKBOT_CHAT_POST_MESSAGE" },
      ]},
      { name: "to", label: "To Email", type: "text", placeholder: "recipient@example.com", showWhen: { field: "action", value: "GMAIL_SEND_EMAIL" } },
      { name: "subject", label: "Subject", type: "text", placeholder: "Email subject", showWhen: { field: "action", value: "GMAIL_SEND_EMAIL" } },
      { name: "body", label: "Email Body", type: "textarea", placeholder: "Write the email...", showWhen: { field: "action", value: "GMAIL_SEND_EMAIL" } },
      { name: "channel", label: "Slack Channel", type: "text", placeholder: "#general or channel ID", showWhen: { field: "action", value: "SLACKBOT_CHAT_POST_MESSAGE" } },
      { name: "message", label: "Slack Message", type: "textarea", placeholder: "Write the message...", showWhen: { field: "action", value: "SLACKBOT_CHAT_POST_MESSAGE" } },
      { name: "parameters", label: "Advanced Params JSON", type: "textarea", placeholder: "{}" },
      { name: "credential_id", label: "Credential", type: "credential" },
    ],
  },
];
