name: Deploy to EC2

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ${{ secrets.EC2_PATH }}
            git fetch origin testing
            git reset --hard origin/testing

            # Inject the GitHub Variable into the .env file before starting Docker
            echo "ALLOWED_HOST=${{ vars.ALLOWED_HOST }}" >> .env

            docker compose up -d --build
