name: Deploy to EC2

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ${{ secrets.EC2_PATH }}
            git fetch origin testing
            git reset --hard origin/testing

            # Inject the GitHub Variables into the .env file before starting Docker
            sed -i '/^ALLOWED_HOST=/d' .env
            sed -i '/^VITE_API_URL=/d' .env
            sed -i '/^ALLOWED_ORIGINS=/d' .env
            
            echo "ALLOWED_HOST=${{ vars.ALLOWED_HOST }}" >> .env
            echo "VITE_API_URL=${{ vars.VITE_API_URL }}" >> .env
            echo "ALLOWED_ORIGINS=${{ vars.ALLOWED_ORIGINS }}" >> .env

            docker compose up -d --build
