name: Deploy to EC2

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ${{ secrets.EC2_PATH }}
            git fetch origin testing
            git reset --hard origin/testing

            # Inject the GitHub Variables into the .env file before starting Docker
            sed -i '/^ALLOWED_HOST=/d' .env
            sed -i '/^VITE_API_URL=/d' .env
            sed -i '/^ALLOWED_ORIGINS=/d' .env
            sed -i '/^DATABASE_URL=/d' .env
            sed -i '/^SECRET_KEY=/d' .env
            sed -i '/^GOOGLE_CLIENT_ID=/d' .env
            sed -i '/^GOOGLE_CLIENT_SECRET=/d' .env
            sed -i '/^GOOGLE_REDIRECT_URI=/d' .env
            sed -i '/^FRONTEND_URL=/d' .env
            sed -i '/^GOOGLE_AUTH_URL=/d' .env
            sed -i '/^GOOGLE_TOKEN_URL=/d' .env
            sed -i '/^GOOGLE_USERINFO_URL=/d' .env
            sed -i '/^REDIS_URL=/d' .env
            
            echo "ALLOWED_HOST=${{ vars.ALLOWED_HOST }}" >> .env
            echo "VITE_API_URL=${{ vars.VITE_API_URL }}" >> .env
            echo "ALLOWED_ORIGINS=${{ vars.ALLOWED_ORIGINS }}" >> .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
            echo "GOOGLE_REDIRECT_URI=${{ vars.GOOGLE_REDIRECT_URI }}" >> .env
            echo "FRONTEND_URL=${{ vars.FRONTEND_URL }}" >> .env
            echo "GOOGLE_AUTH_URL=${{ vars.GOOGLE_AUTH_URL }}" >> .env
            echo "GOOGLE_TOKEN_URL=${{ vars.GOOGLE_TOKEN_URL }}" >> .env
            echo "GOOGLE_USERINFO_URL=${{ vars.GOOGLE_USERINFO_URL }}" >> .env
            echo "REDIS_URL=redis://redis:6379/0" >> .env

            docker compose -f docker-compose.prod.yml up -d --build
